### ISSUE TITLE
How to install a standalone SSO server with this repo ?

### ISSUE THREAD

**Issue by spyesx** [ramdannur/laravel-sso-passport#1]
Hello !

I'm curious about this SSO server. Did you plan to add more documentation and/or an API?

I'd like to now how to install it as a standalone SSO server but we can see some different services on many screenshots.

Thx

**Comment by ramdannur** [comment]
Hi!

I have added a little change to the name of the project.

To run this SSO server you need to manually migrate and seed each of web apps (sales management as a provider, mail system as a branch), or you can import with existing SQL that I have uploaded in the database folder. And don't forget to generate passport key.

You can see the complete configuration in Laravel's documentation for installation.

After you have done with the installation, you can run the service with php artisan serve as I wrote in the readme.

Actually, this is just a simple project example of implementing SSO Auth in the Laravel framework with a passport for its API connection. I don't think to add more documentation or API.

**Comment by spyesx** [comment]
Thank you :)

**Comment by ramdannur** [comment]
Sure, if you have any questions feel free to ask.
